name: 9txCore
main: org.realcodingteam.plan9.NtxPlugin
version: 2.0.0
authors: [Danny, ProfLuz]
softdepend: [Essentials]
api-version: 1.13
commands:
   donor:
      description: Opens the donor menu
      usage: /<command>
      aliases: [d, ntx, tx, 0tx, 9tx]
   staff:
      description: Staff chat
      usage: /<command> [msg]
      aliases: [staffchat, schat, sc]
   reload:
      description: Reloads menus
      usage: /<command>
      aliases: [menureload, 9txreload, 9txrl, txrl]
permissions:
   ntx.*:
      description: Gives access to all permissions
      children:
         ntx.build: true
         ntx.donor: true
         ntx.donor.add: true
         ntx.donor.nick: true
         ntx.staff: true
         ntx.item: true
         ntx.end: true
   ntx.donor:
      description: Gives access to the donor command
   ntx.donor.add:
      description: Gives access to the donor add subcommand
   ntx.donor.nick:
      description: Gives access to changing name color
   ntx.build:
      description: Allows building on the nether roof
   ntx.staff:
      description: Gives access to staff chat
   ntx.item:
      description: Allows displaying items in chat
   ntx.soldier:
      description: Rank permission
   ntx.knight:
      description: Rank permission
   ntx.general:
      description: Rank permission
   ntx.king:
      description: Rank permission
   ntx.emperor:
      description: Rank permission
   ntx.end:
      description: Rank permission