name: NtxCore
main: org.realcodingteam.plan9.NtxPlugin
version: 1.0
author: Danny
api-version: 1.13
commands:
   staff:
      description: Staff chat
      usage: /<command> [msg]
      aliases: [staffchat, schat, sc]
   patch:
      description: Patch command
      usage: /<command> [subcommand]