name: NtxCore
main: me.daniel.ntx.NtxPlugin
version: 1.0
author: Danny
api-version: 1.13
commands:
   staff:
      description: Staff chat
      usage: /<command> [msg]
      aliases: [staffchat, schat, sc]