name: 9txCore
main: org.realcodingteam.plan9.NtxPlugin
version: 1.1.6
authors: [Danny, ProfLuz]
softdepend: [ProtocolLib, Essentials]
api-version: 1.13
commands:
   donor:
      description: Opens the donor menu
      usage: /<command>
      aliases: [d]
   staff:
      description: Staff chat
      usage: /<command> [msg]
      aliases: [staffchat, schat, sc]
permissions:
   ntx.*:
      description: Gives access to all permissions
      children:
         ntx.build: true
         ntx.donor: true
         ntx.donor.add: true
         ntx.staff: true
   ntx.donor:
      description: Gives access to the donor command
   ntx.donor.add:
      description: Gives access to the donor add subcommand
   ntx.build:
      description: Allows building on the nether roof
   ntx.staff:
      description: Gives access to staff chat